database:
    master:
        host: localhost
        username: root
        password:
        log-query: false
        dbname: dababase
    slave:
        host: localhost
        username: root
        password:
        log-query: false
        dbname: dababase
orm:
    cast-on-hydrate: true
    metadata-cache: memory

application:
    debugger: true
    mailer: true
    log:
        requests: false
        errors: false
        internal: false
        files:
            requests: /app/logs/requests.log
            errors: /app/logs/errors.log
            internal: /app/logs/internal.log
            query: /app/logs/query.log

    links:
        origin: "*"
        project: https://woxapp.com/
        api: https://woxapp.com/

external:
    redis:
        host: 127.0.0.1
        port: 6379
    memcached:
        host: 127.0.0.1
        port: 11211
    kafka:
        host: 127.0.0.1
        port: 9092
        version: 2.0.0
    gearman:
        host: 127.0.0.1
        port: 4730
    smtp:
        host: smtp.gmail.com
        port: 465
        username: test@woxapp.com
        sender: test@woxapp.com
        password: WOXAPP12345
